config/routes.rb
Rails.application.routes.draw do

  resources :child_notes, except: [:index]
  #resources :links

  devise_for :users
  root to: 'notes#index'

  resources :notes do

    resources :checklist_items
    resources :folds, only: [:create, :update, :destroy]
    resources :links

    member do
      put 'move_to_position'
      put 'toggle_favorite'
      put 'toggle_deleted'
      put 'delete_asset'
    end

    collection do
      get 'favorites'
      get 'deleted'
    end
  end

  resources :tags



  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:index, :show, :create, :update, :destroy] do
      resources :checklist_items, only: [:index, :show, :create, :update, :destroy]
      resources :assets, only: [:index, :show, :create, :destroy]
      resources :links, only: [:index, :create, :destroy]
      resources :folds, only: [:index, :show, :create, :update, :destroy]
    end
    resources :tags, only: [:index, :create, :update, :destroy]
    resource :user, only: [:create, :update, :destroy]
    resource :token, only: [:create]
  end
end

app/models/child_note.rb
class ChildNote < Note
  belongs_to :parent, class_name: "Note"

  validates_presence_of :parent_id
end

app/models/note.rb
class Note < ActiveRecord::Base
  include Sortable
  before_destroy :remove_linked

  belongs_to :user

  has_many :folds, dependent: :destroy

  has_many :links, dependent: :destroy
  has_many :linked_notes, through: :links

  has_many :checklist_items, dependent: :destroy

  has_many :assets, dependent: :destroy
  accepts_nested_attributes_for :assets, allow_destroy: true

  has_and_belongs_to_many :tags, join_table: 'note_tags'

  has_many :child_notes, class_name: 'Note', foreign_key: 'parent_id', dependent: :destroy

  scope :search, -> (search) do
    where(
      'title LIKE :search OR body LIKE :search',
      search: "%#{search}%"
    )
  end

  private

    def remove_linked
      Link.where(linked_note: self.id).destroy_all
    end

end

app/controllers/child_notes_controller.rb
class ChildNotesController < ApplicationController
  before_action :set_child_note, only: [:show, :edit, :update, :destroy]
  before_action :set_notes_and_tags, only: [:new, :create, :edit, :update]
  # GET /child_notes
  # def index
  #   @child_notes = ChildNote.all
  # end

  # GET /child_notes/1
  def show
    @note = @note.becomes(Note)
    @notes = current_user.notes
    render 'notes/show'
  end

  # GET /child_notes/new
  def new
    @note = ChildNote.new
  end

  # GET /child_notes/1/edit
  def edit
  end

  # POST /child_notes
  def create
    @note = ChildNote.new(child_note_params)

    if @note.save
      # @note.reload
      redirect_to @note.parent, notice: 'Se ha creado la nota.'
    else
      render :new
    end
  end

  # PATCH/PUT /child_notes/1
  def update
    if @note.update(child_note_params)
      redirect_to @note.parent, notice: 'La nota se actualizo.'
    else
      render :edit
    end
  end

  # DELETE /child_notes/1
  def destroy
    note = @note.note
    @note.destroy
    redirect_to note, notice: 'Se eliminó la nota/'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child_note
      @note = ChildNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_note_params
      params.require(:child_note).permit(
        :title,
        :body,
        :favorite,
        :parent_id,
        { assets_attributes: [:id, :_destroy, :file] }
      )
    end

    def set_notes_and_tags
      @notes = current_user.notes
      @tags = current_user.tags
    end
end

app/helpers/child_notes_helper.rb
module ChildNotesHelper
end

app/views/child_notes/_form.html.erb
<%= form_for(@note, builder: IdeonFormBuilder, html: { multipart: true } ) do |f| %>
  <%= render 'shared/errors', object: @note %>

  <% if @note.persisted? %>
    <%= f.container do %>
      <%= f.label_collection_select :parent_id, current_user.notes, :id, :title, { selected: @note.id } %>
    <% end %>
  <% else %>
    <%= f.hidden_field :parent_id, value: params[:note_id] %>
  <% end %>

  <%= f.container do %>
    <%= f.text_field :title, placeholder: 'Titulo', class: 'form-control' %>
  <% end %>

  <%= f.container do %>
    <%= f.text_area :body, rows: rows_for(@note), placeholder: 'Lorem ipsum dolor sit amec...', class: 'form-control' %>
  <% end %>

  <%= f.check_box :favorite %>

  <%= collection_check_boxes :note, :tag_ids, @tags, :id, :name do |builder| %>
    <%= builder.label(class: 'check_box') do %>
      <% icon = content_tag(:i, nil, class: 'fa fa-tag') %>
      <% checkbox = builder.check_box(class: 'check_box') %>
      <%= "#{checkbox} #{builder.text} #{icon}".html_safe %>
    <% end %>
  <% end %>

  <div id="assets-container">
    <%= f.fields_for :assets do |fa| %>
      <%= f.container do %>
        <%= fa.hidden_field :id %>

        <div class="row">
          <div class="col-xs-1">
            <%= image_tag fa.object.file.url, height: '80px', width: '80px' %>
          </div>
          <div class="col-xs-1 col-xs-offset-1 col-md-offset-0">
            <%= fa.check_box :_destroy, { checked: false } %>
          </div>
        </div>

        <%= fa.file_field :file %>
      <% end %>
    <% end %>
  </div>
  <%= link_to 'Agregar imagen', '#', class: "btn btn-primary", id: 'new-image-button-child-note' %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/child_notes/edit.html.erb
<h1>Editar Nota Hija</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/child_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Child Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @child_notes.each do |child_note| %>
      <tr>
        <td><%= child_note.title %></td>
        <td><%= child_note.body %></td>
        <td><%= link_to 'Show', child_note %></td>
        <td><%= link_to 'Edit', edit_child_note_path(child_note) %></td>
        <td><%= link_to 'Destroy', child_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child note', new_child_note_path %>

app/views/child_notes/new.html.erb
<h1>Crear nota hija</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/child_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @child_note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @child_note.body %>
</p>

<%= link_to 'Edit', edit_child_note_path(@child_note) %> |
<%= link_to 'Back', child_notes_path %>