config/routes.rb
Rails.application.routes.draw do

  resources :child_notes, except: [:index]
  #resources :links

  devise_for :users
  root to: 'notes#index'

  resources :notes do

    resources :checklist_items
    resources :folds, only: [:create, :update, :destroy]
    resources :links

    member do
      put 'move_to_position'
      put 'toggle_favorite'
      put 'toggle_deleted'
      put 'delete_asset'
    end

    collection do
      get 'favorites'
      get 'deleted'
    end
  end

  resources :tags



  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:index, :show, :create, :update, :destroy] do
      resources :checklist_items, only: [:index, :show, :create, :update, :destroy]
      resources :assets, only: [:index, :show, :create, :destroy]
      resources :links, only: [:index, :create, :destroy]
      resources :folds, only: [:index, :show, :create, :update, :destroy]
    end
    resources :tags, only: [:index, :create, :update, :destroy]
    resource :user, only: [:create, :update, :destroy]
    resource :token, only: [:create]
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  include Sortable
  before_destroy :remove_linked

  belongs_to :user

  has_many :folds, dependent: :destroy

  has_many :links, dependent: :destroy
  has_many :linked_notes, through: :links

  has_many :checklist_items, dependent: :destroy

  has_many :assets, dependent: :destroy
  accepts_nested_attributes_for :assets, allow_destroy: true

  has_and_belongs_to_many :tags, join_table: 'note_tags'

  has_many :child_notes, class_name: 'Note', foreign_key: 'parent_id', dependent: :destroy

  scope :search, -> (search) do
    where(
      'title LIKE :search OR body LIKE :search',
      search: "%#{search}%"
    )
  end

  private

    def remove_linked
      Link.where(linked_note: self.id).destroy_all
    end

end

app/controllers/api/notes_controller.rb
class Api::NotesController < Api::ApplicationController

  before_action :set_note, only: [:show, :update, :destroy]

  def index
    @notes = current_user.notes_and_child_notes
  end

  def show
  end

  def create
    if params[:note][:parent_id] == 0
      @note = Note.new(note_params)
    else
      @note = ChildNote.new(note_params)
    end
    @note.user = current_user

    unless @note.save
      render json: @note.errors, status: :unprocessable_entity
    end
  end

  def update
    if params[:note][:parent_id] == 0
      @note.type = nil
    else
      @note.type = 'ChildNote'
    end
    unless @note.update(note_params)
      render json: @note.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy
    head :ok
  end

  private

    def set_note
      @note = current_user.find_note_or_child_note(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :body, :favorite, :deleted, :position, :parent_id, { tag_ids: [] })
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [
                            :show,
                            :toggle_favorite,
                            :edit,
                            :update,
                            :destroy,
                            :toggle_deleted
                          ]
  before_action :set_tags, only: [:index, :favorites, :new, :create, :edit, :update, :deleted]

  # GET /notes
  def index
    @notes = current_user.notes.where(deleted: false)
    filter_by_tag(params[:tag])
    @notes = @notes.search(params[:search])
  end

  # GET /notes/favorites
  def favorites
    @notes = current_user.favorite_notes
    filter_by_tag(params[:tag])
    render 'index'
  end

  #GET /notes/deleted
  def deleted
    @notes = current_user.deleted_notes
    filter_by_tag(params[:tag])
    render 'index'
  end


  # GET /notes/1
  def show
    @notes = current_user.notes.where.not(deleted: true, id: @note.id)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to @note, notice: 'La nota fue creada correctamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'La nota fue actualizada correctamente.'
    else
      render :edit
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    redirect_to notes_url, notice: 'La nota fue borrada correctamente.'
  end

  # PUT /notes/1/toggle_favorite
  def toggle_favorite
    @note.toggle!(:favorite)
    respond_to do |format|
      format.html { redirect_to @note, notice: 'La nota fue actualizada correctamente.' }
      format.js { render }
    end
  end

  # PUT /notes/1/toggle_deleted
  def toggle_deleted
    @note.toggle!(:deleted)
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'La nota fue actualizada correctamente.' }
      format.js { render }
    end
  end

  def move_to_position
    note = Note.find(params[:id])
    note.move_to_position(params[:position].to_i)
    render json: { status: :ok }
  end

  def delete_asset
    @note = Note.find(params[:id])
    @note.assets.find_by_id(params[:asset_id]).destroy
    redirect_to @note, notice: 'La nota fue actualizada correctamente.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(
        { tag_ids: [] },
        :title,
        :body,
        :favorite,
        :deleted,
        { assets_attributes: [:id, :_destroy, :file] }
      )
    end

    def set_tags
      @tags = current_user.tags
    end

    def filter_by_tag(selected_tag)
      if selected_tag.present? && selected_tag.to_i > 0
        @notes = current_user.notes.joins(:tags).where('tags.id = ?', selected_tag.to_i)
      end
    end
end

app/helpers/api/notes_helper.rb
module Api::NotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def icon(note)
    if note.favorite
      'star'
    else
      'star-o'
    end
  end

  def deleted_icon(note)
    if note.deleted
      'check'
    else
      'trash-o'
    end
  end

  def icon_text(note)
    if note.deleted
      'Reestablecer'
    else
      'Eliminar'
    end
  end

  def rows_for(note)
    if note.body
      note.body.length / 150 + 4
    else
      4
    end
  end
end

app/views/notes/_form.html.erb
<%= form_for(@note, builder: IdeonFormBuilder, html: { multipart: true } ) do |f| %>
  <%= render 'shared/errors', object: @note %>

  <%= f.container do %>
    <%= f.text_field :title, placeholder: 'Titulo', class: 'form-control' %>
  <% end %>

  <%= f.container do %>
    <%= f.text_area :body, rows: rows_for(@note), placeholder: 'Lorem ipsum dolor sit amec...', class: 'form-control' %>
  <% end %>

  <%= f.check_box :favorite %>

  <%= collection_check_boxes :note, :tag_ids, @tags, :id, :name do |builder| %>
    <%= builder.label(class: 'check_box') do %>
      <% icon = content_tag(:i, nil, class: 'fa fa-tag') %>
      <% checkbox = builder.check_box(class: 'check_box') %>
      <%= "#{checkbox} #{builder.text} #{icon}".html_safe %>
    <% end %>
  <% end %>

  <div id="assets-container">
    <%= f.fields_for :assets do |fa| %>
      <%= f.container do %>
        <%= fa.hidden_field :id %>

        <div class="row">
          <div class="col-xs-1">
            <%= image_tag fa.object.file.url, height: '80px', width: '80px' %>
          </div>
          <div class="col-xs-1 col-xs-offset-1 col-md-offset-0">
            <%= fa.check_box :_destroy, { checked: false } %>
          </div>
        </div>

        <%= fa.file_field :file %>
      <% end %>
    <% end %>
  </div>

  <%= link_to 'Agregar imagen', '#', class: "btn btn-primary", id: 'new-image-button' %>
  
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/notes/_modal.html.erb
<div class="modal fade" id="<%= "#{member.id}-#{member.title.parameterize}" %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= member.title %> <%= fa_icon(icon(@note)) %></h4>
      </div>
      <div class="modal-body">
        <p class="lead">
          <%= member.body %>
        </p>

        <% member.assets.each do |asset| %>
          <div class="media">
            <div class="media-left">
              <a>
                <%= image_tag asset.file.url, height: '90px', class: 'media-object img-circle', width: '90px' %>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">Eliminar </h4>
              <%= link_to fa_icon('trash-o'), delete_asset_note_path(@note, asset_id: asset.id), method: :put, data: { confirm: 'Estas seguro?' } %>
            </div>
          </div>
        <% end %>
        <% if member.assets.count == 0 %>
          No tiene archivos adjuntos aún, haz click <%= link_to 'aquí', edit_child_note_path(member) %> para agregar archivos
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= link_to "Ver", member, class: "btn btn-primary" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/notes/edit.html.erb
<h1>Editar Nota</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/notes/index.html.erb
<h1>Notas</h1>
<div class="row">
  <% if params[:action] != 'index' || params[:search].present? %>
    <%= link_to fa_icon('undo', text: 'Regresar'), notes_path, class: 'btn btn-warning btn-lg' %>
  <% end %>
  <%= link_to fa_icon('plus', text: 'Nueva Nota'), new_note_path, class: 'btn btn-primary btn-lg pull-right' %>
  <% if params[:action] != 'favorites' %>
    <%= link_to fa_icon('star', text: 'Filtrar favoritas'), favorites_notes_path, class: 'btn btn-info btn-lg pull-right' %>
  <% end %>
  <% if params[:action] != 'deleted' %>
    <%= link_to fa_icon('trash-o', text: 'Notas Archivadas'), deleted_notes_path, class: 'btn btn-info btn-lg pull-right' %>
  <% end %>
</div>

<div class="row">
  <% if @notes.count > 0 %>
    <%= select_tag(
      'Mostrar etiqueta',
      options_from_collection_for_select(
        @tags,
        :id,
        :name,
        params[:tag]
      ),
      include_blank: 'Todas',
      id: 'tag-select',
      class: 'form-control',
      style: 'margin-top: 10px;'
    ) %>
  <% end %>
</div>

<% if @notes.count > 0 %>
  <table class="table table-hover table-stripped">
    <tbody id="sortable">
      <% @notes.each do |note| %>
        <tr
          data-id="<%= note.id %>"
          data-url="<%= move_to_position_note_path(note) %>"
        >
          <td class="draggable"><%= fa_icon('bars') %></td>
          <td><%= note.title.truncate(16) %></td>
          <td><%= note.body.truncate(45) %></td>
          <td style="width: 30px;" id="favorite-note-<%= note.id %>"><%= link_to fa_icon(icon(note)), toggle_favorite_note_path(note), remote: true, method: :put %></td>
          <td style="width: 30px;"><%= link_to fa_icon('search'), note %></td>
          <td style="width: 30px;"><%= link_to fa_icon('pencil'), edit_note_path(note) %></td>
          <td style="width: 30px;" id="deleted-note-<%= note.id %>"><%= link_to fa_icon(deleted_icon(note)), toggle_deleted_note_path(note), method: :put, data: { confirm: 'Archivar?' } %></td>
          <% if note.deleted %>
            <td style="width: 30px;"><%= link_to fa_icon('times'), note, method: :delete, data: { confirm: 'Borrar permanentemente?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="hero text-center">Aún no hay notas en esta sección</p>
  <p class="hero text-center">
    <% if params[:search].present? %>
      No hay notas que coincidan con su búsqueda.
    <% elsif params[:action] == 'index' %>
      Para agregar una nueva nota haz click en el botón "Nuevo"
    <% elsif params[:action] == 'deleted' %>
      Para archivar una nota, haz clik en el botón eliminar de las notas.
    <% elsif params[:action] == 'favorites' %>
      Para marcar una nota como favorita haz click en el botón de favorita en la nota.
    <% end %>
  </p>
<% end %>

app/views/notes/new.html.erb
<h1>Nueva Nota</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/notes/show.html.erb
<div class="pull-right">
  <%= link_to 'Editar', edit_note_path(@note), class: 'btn btn-info' %>
  <%= link_to 'Todas las notas', notes_path, class: 'btn btn-primary' %>
</div>

<h2>
  <%= @note.title %> <%= fa_icon(icon(@note)) %>
</h2>

<div class="well">
  <%= @note.body.html_safe %>
</div>

<h3>Pliegues</h3>
<% @note.folds.each do |fold| %>
  <a data-toggle="collapse"
      href="#fold-collapse-<%= fold.id %>"
      aria-expanded="false"
      aria-controls="collapseExample">
    <%= fold.content.truncate(12) %> <%= fa_icon('eye') %>
  </a>
  <%= link_to [@note, fold], method: :delete do %>
    <%= fa_icon('trash-o') %>
  <% end %>
  <div class="collapse" id="fold-collapse-<%= fold.id %>">
    <div class="well fold-well"
        data-note-id="<%= @note.id %>"
        data-fold-id="<%= fold.id %>"
        data-dirty="false"><%= fold.content %></div>
  </div>
  <br>
<% end %>

<%= form_for([@note, @note.folds.build], html: { class: 'form-inline' }) do |f| %>
  <div class="form-group col-xs-7">
    <%= f.text_area :content, placeholder: 'lorem ipsum', class: 'form-control', style: 'width: 100%;' %>
  </div>
  <%= f.submit 'Crear pliegue', class: 'btn btn-success' %>
<% end %>
<br>
<h3>Elementos de la lista</h3>
<% @note.checklist_items.each do |checklist_item| %>
  <div>
    <%= fa_icon(checklist_item.fa_checked) %>
    <%= checklist_item.description %>
    <%= link_to fa_icon('times'), [checklist_item.note, checklist_item], method: :delete, data: { confirm: 'Estás seguro?' } %>
  </div>
<% end %>
<%= form_for([@note, @note.checklist_items.build], html: { class: 'form-inline' }) do |f| %>
    <div class="checkbox">
      <%= label_tag do %>
        <%= f.check_box :checked %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.text_field :description, placeholder: 'Darle de comer al perro', class: 'form-control' %>
    </div>
    <%= f.submit 'Crear', class: 'btn btn-success' %>
<% end %>

<h3>Notas Hijas:</h3>
<%= link_to 'Agregar', new_child_note_path(note_id: @note.id), class: 'btn btn-success' %>
<ul>
  <% @note.child_notes.each do |child_note| %>
    <li>
      <%= link_to(
          child_note.title,
          "##{child_note.id}-#{child_note.title.parameterize}",
          data: {
            toggle: "modal",
            target: "##{child_note.id}-#{child_note.title.parameterize}",
          }
        ) %> - <%= link_to fa_icon('pencil'), edit_child_note_path(child_note) %> | <%= link_to fa_icon('trash'), child_note_path(child_note), method: :delete %>
    </li>
    <%= render "modal", member: child_note %>
  <% end %>
</ul>

<h3>Archivos adjuntos</h3>
<% @note.assets.each do |asset| %>
  <div class="media">
    <div class="media-left">
      <a>
        <%= image_tag asset.file.url, height: '90px', class: 'media-object img-circle', width: '90px' %>
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Eliminar </h4>
      <%= link_to fa_icon('trash-o'), delete_asset_note_path(@note, asset_id: asset.id), method: :put, data: { confirm: 'Estas seguro?' } %>
    </div>
  </div>
<% end %>
<% if @note.assets.count == 0 %>
  <p class="lead">No tiene archivos adjuntos aún, haz click <%= link_to 'aquí', edit_note_path(@note) %> para agregar archivos</p>
<% end %>


<h3>Notas Vinculadas:</h3>
<ul>
  <% @note.links.each do |link| %>
    <li>
      <%= link_to link.linked_note.title, link.linked_note %>
      <%= link_to fa_icon('trash-o', text: 'Eliminar vinculo'), [link.note, link], method: :delete, data: { confirm: 'Estás seguro?' } %>
    </li>
  <% end %>
</ul>
<div class = "list">
  <%= form_for([@note, @note.links.build], html: { class: 'form-inline' }) do |f| %>
    <%= collection_check_boxes :link, :linked_note_id, @notes, :id, :title do |builder| %>
      <%= builder.label(class: 'check_box') do %>
        <% checkbox = builder.check_box(class: 'check_box') %>
        <%= "#{checkbox} #{builder.text}".html_safe %>
      <% end %>
    <% end %>
    <%= f.submit 'Vincular', class: 'btn btn-success' %>
  <% end %>
</div>

<br>
<%= link_to "Regresar", :back, class: 'btn btn-danger' %>

app/views/notes/toggle_deleted.js.erb
$('#deleted-note-' + '<%= @note.id %>').html('<%= escape_javascript(link_to(fa_icon(deleted_icon(@note), text: icon_text(@note)), toggle_deleted_note_path(@note), method: :put)) %>')

app/views/notes/toggle_favorite.js.erb
$('#favorite-note-' + '<%= @note.id %>').html('<%= escape_javascript(link_to(fa_icon(icon(@note)), toggle_favorite_note_path(@note), remote: true, method: :put)) %>')