config/routes.rb
Rails.application.routes.draw do

  resources :child_notes, except: [:index]
  #resources :links

  devise_for :users
  root to: 'notes#index'

  resources :notes do

    resources :checklist_items
    resources :folds, only: [:create, :update, :destroy]
    resources :links

    member do
      put 'move_to_position'
      put 'toggle_favorite'
      put 'toggle_deleted'
      put 'delete_asset'
    end

    collection do
      get 'favorites'
      get 'deleted'
    end
  end

  resources :tags



  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:index, :show, :create, :update, :destroy] do
      resources :checklist_items, only: [:index, :show, :create, :update, :destroy]
      resources :assets, only: [:index, :show, :create, :destroy]
      resources :links, only: [:index, :create, :destroy]
      resources :folds, only: [:index, :show, :create, :update, :destroy]
    end
    resources :tags, only: [:index, :create, :update, :destroy]
    resource :user, only: [:create, :update, :destroy]
    resource :token, only: [:create]
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user

  has_and_belongs_to_many :notes, join_table: 'note_tags'
end

app/controllers/api/tags_controller.rb
class Api::TagsController < Api::ApplicationController

  before_action :set_tag, only: [:update, :destroy]

  def index
    @tags = current_user.tags
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user

    unless @tag.save
      render json: @tag.errors, status: :unprocessable_entity
    end
  end

  def update
    unless @tag.update(tag_params)
      render json: @tag.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy
    head :ok
  end

  private

    def set_tag
      @tag = current_user.tags.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [
                            :show,
                            :toggle_favorite,
                            :edit,
                            :update,
                            :destroy
                          ]

  # GET /tags
  def index
    @tags = current_user.tags
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user

    if @tag.save
      redirect_to tags_path, notice: 'La etiqueta fue creada correctamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'La etiqueta fue actualizada correctamente.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'La etiqueta fue borrada correctamente.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(
        :name,
      )
    end
end

app/helpers/api/tags_helper.rb
module Api::TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag, builder: IdeonFormBuilder) do |f| %>
  <%= render 'shared/errors', object: @tag %>

  <%= f.container do %>
    <%= f.label_text_field :name %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Editar Etiqueta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/tags/index.html.erb
<h1>Etiquetas</h1>
<%= link_to fa_icon('plus', text: 'Nueva etiqueta'), new_tag_path, class: 'btn btn-primary btn-lg pull-right' %>

<% if @tags.count > 0 %>
  <table class="table table-hover table-stripped">

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td style="width: 30px;"><%= link_to fa_icon('search'), tag %></td>
          <td style="width: 30px;"><%= link_to fa_icon('pencil'), edit_tag_path(tag) %></td>
          <td style="width: 30px;"><%= link_to fa_icon('trash-o'), tag, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="lead text-center">No has creado etiquetas.</p>
  <p class="lead text-center">Para crera una etiqueta haz click en el botón "Nuevo"</p>
<% end %>

app/views/tags/new.html.erb
<h1>Nueva Etiqueta</h1>

<%= render 'form' %>

<%= link_to 'Regresar', :back, class: 'btn btn-warning' %>

app/views/tags/show.html.erb
<h2>
  <%= @tag.name %>
</h2>

<%= link_to 'Editar', edit_tag_path(@tag), class: 'btn btn-info' %>
<%= link_to 'Todas las etiquetas', tags_path, class: 'btn btn-primary' %>