config/routes.rb
Rails.application.routes.draw do

  resources :child_notes, except: [:index]
  #resources :links

  devise_for :users
  root to: 'notes#index'

  resources :notes do

    resources :checklist_items
    resources :folds, only: [:create, :update, :destroy]
    resources :links

    member do
      put 'move_to_position'
      put 'toggle_favorite'
      put 'toggle_deleted'
      put 'delete_asset'
    end

    collection do
      get 'favorites'
      get 'deleted'
    end
  end

  resources :tags



  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:index, :show, :create, :update, :destroy] do
      resources :checklist_items, only: [:index, :show, :create, :update, :destroy]
      resources :assets, only: [:index, :show, :create, :destroy]
      resources :links, only: [:index, :create, :destroy]
      resources :folds, only: [:index, :show, :create, :update, :destroy]
    end
    resources :tags, only: [:index, :create, :update, :destroy]
    resource :user, only: [:create, :update, :destroy]
    resource :token, only: [:create]
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'IDEON', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <%= content_tag :li, class: active_path(:notes) do %>
            <%= link_to 'Notas', notes_path %>
          <% end %>
          <%= content_tag :li, class: active_path(:tags) do %>
            <%= link_to 'Etiquetas', tags_path %>
          <% end %>
        <% end %>
      </ul>
      <% if current_user %>
        <%= form_tag notes_path, method: :get, class: 'navbar-form navbar-left' do %>
          <div class="form-group">
            <%= text_field_tag(
                :search,
                params[:search],
                placeholder: "Search",
                class: "form-control"
            ) %>
          </div>
          <%= submit_tag 'Ir!', class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ayuda <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if current_user %>
              <li>
                <%= link_to "Mi cuenta", edit_user_registration_path %>
              </li>
              <li><a href="#">Sincronizar notas</a></li>
              <li class="divider"></li>
              <li>
                <%= link_to fa_icon('power-off', text: 'Cerrar sesión'), destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Iniciar Sesión", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Registrarse", new_user_registration_path %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container" id="main-container">
      <div class="jumbotron">
        <% flash.each do |error_type, message| %>
          <div class="alert alert-<%= error_class(error_type) %>" role="alert">
            <span class="sr-only">Error:</span>
            <%= message %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <%= debug params if Rails.env.development? %>
  </body>
</html>